# app/seeds/seed_frutos_secos_y_arboles.py

from app.core.database import SessionLocal
from app.models.cultivo_tipo import CultivoTipo

def run(user_id: int = 2):
    db = SessionLocal()

    variedades = [

        # ============================================================
        # ALMENDROS — VARIEDADES ESPAÑOLAS
        # ============================================================

        {
            "nombre": "Almendro Marcona",
            "nombre_latin": "Prunus dulcis",
            "variedad": "Marcona",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 200,
            "litros_agua_semana": 15,
            "fase_lunar": "Creciente",
            "plagas": ["Barrenillo", "Pulgón"],
            "enfermedades": ["Monilia"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -5,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad premium española; muy apreciada en repostería."
        },
        {
            "nombre": "Almendro Largueta",
            "nombre_latin": "Prunus dulcis",
            "variedad": "Largueta",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 190,
            "litros_agua_semana": 14,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Fusicoccum"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -6,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy típica en Aragón; almendra alargada y sabrosa."
        },
        {
            "nombre": "Almendro Guara",
            "nombre_latin": "Prunus dulcis",
            "variedad": "Guara",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 185,
            "litros_agua_semana": 14,
            "fase_lunar": "Creciente",
            "plagas": ["Barrenillo"],
            "enfermedades": ["Monilia"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -6,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy productiva; muy usada en secano."
        },
        {
            "nombre": "Almendro Ferragnes",
            "nombre_latin": "Prunus dulcis",
            "variedad": "Ferragnes",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 190,
            "litros_agua_semana": 14,
            "fase_lunar": "Creciente",
            "plagas": ["Barrenillo", "Pulgón"],
            "enfermedades": ["Monilia"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -6,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy cultivada en Aragón; almendra grande y sabrosa."
        },
        {
            "nombre": "Almendro Ferraduel",
            "nombre_latin": "Prunus dulcis",
            "variedad": "Ferraduel",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 195,
            "litros_agua_semana": 14,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Fusicoccum"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -6,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente; ideal para secano."
        },
        {
            "nombre": "Almendro Soleta",
            "nombre_latin": "Prunus dulcis",
            "variedad": "Soleta",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 185,
            "litros_agua_semana": 13,
            "fase_lunar": "Creciente",
            "plagas": ["Barrenillo"],
            "enfermedades": ["Monilia"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -6,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad moderna española; muy productiva."
        },
        {
            "nombre": "Almendro Belona",
            "nombre_latin": "Prunus dulcis",
            "variedad": "Belona",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 185,
            "litros_agua_semana": 13,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Monilia"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -6,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy usada en Castilla-La Mancha; almendra de alta calidad."
        },
        {
            "nombre": "Almendro Marta",
            "nombre_latin": "Prunus dulcis",
            "variedad": "Marta",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 180,
            "litros_agua_semana": 13,
            "fase_lunar": "Creciente",
            "plagas": ["Barrenillo"],
            "enfermedades": ["Fusicoccum"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -6,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Floración tardía; evita heladas."
        },

        # ============================================================
        # NOGALES — VARIEDADES CULTIVADAS EN ESPAÑA
        # ============================================================

        {
            "nombre": "Nogal Franquette",
            "nombre_latin": "Juglans regia",
            "variedad": "Franquette",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 220,
            "litros_agua_semana": 25,
            "fase_lunar": "Creciente",
            "plagas": ["Barrenador"],
            "enfermedades": ["Antracnosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -8,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy cultivado en Castilla y León."
        },
        {
            "nombre": "Nogal Serr",
            "nombre_latin": "Juglans regia",
            "variedad": "Serr",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 210,
            "litros_agua_semana": 24,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca del nogal"],
            "enfermedades": ["Antracnosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -7,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy productivo; nuez grande y clara."
        },

        # ============================================================
        # AVELLANOS — VARIEDADES ESPAÑOLAS
        # ============================================================

        {
            "nombre": "Avellano Negreta",
            "nombre_latin": "Corylus avellana",
            "variedad": "Negreta",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 200,
            "litros_agua_semana": 18,
            "fase_lunar": "Creciente",
            "plagas": ["Balanino"],
            "enfermedades": ["Bacteriosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad catalana muy apreciada."
        },
        {
            "nombre": "Avellano Pauetet",
            "nombre_latin": "Corylus avellana",
            "variedad": "Pauetet",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 195,
            "litros_agua_semana": 18,
            "fase_lunar": "Creciente",
            "plagas": ["Balanino"],
            "enfermedades": ["Bacteriosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy cultivado en Tarragona."
        },
        {
            "nombre": "Avellano Gironell",
            "nombre_latin": "Corylus avellana",
            "variedad": "Gironell",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 200,
            "litros_agua_semana": 18,
            "fase_lunar": "Creciente",
            "plagas": ["Balanino", "Pulgón"],
            "enfermedades": ["Bacteriosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad catalana muy productiva; fruto pequeño y aromático."
        },
        {
            "nombre": "Avellano Morell",
            "nombre_latin": "Corylus avellana",
            "variedad": "Morell",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 195,
            "litros_agua_semana": 18,
            "fase_lunar": "Creciente",
            "plagas": ["Balanino"],
            "enfermedades": ["Bacteriosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy cultivado en Tarragona; avellana de gran calidad."
        },
        {
            "nombre": "Avellano Pau Ferrat",
            "nombre_latin": "Corylus avellana",
            "variedad": "Pau Ferrat",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 205,
            "litros_agua_semana": 19,
            "fase_lunar": "Creciente",
            "plagas": ["Balanino"],
            "enfermedades": ["Bacteriosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad tradicional catalana; fruto grande y dulce."
        },
        {
            "nombre": "Avellano Negret de Girona",
            "nombre_latin": "Corylus avellana",
            "variedad": "Negret Girona",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 200,
            "litros_agua_semana": 18,
            "fase_lunar": "Creciente",
            "plagas": ["Balanino"],
            "enfermedades": ["Bacteriosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente; típica de Girona."
        },
        {
            "nombre": "Avellano Púrpura",
            "nombre_latin": "Corylus maxima",
            "variedad": "Purpurea",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 200,
            "litros_agua_semana": 18,
            "fase_lunar": "Creciente",
            "plagas": ["Balanino", "Pulgón"],
            "enfermedades": ["Bacteriosis"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 18,
            "temperatura_minima": -10,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Hojas púrpuras muy decorativas; avellana grande y aromática."
        }, 

        # ============================================================
        # PISTACHEROS — VARIEDADES ESPAÑOLAS
        # ============================================================
        {
            "nombre": "Pistachero Cornicabra",
            "nombre_latin": "Pistacia terebinthus",
            "variedad": "Cornicabra",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 230,
            "litros_agua_semana": 15,
            "fase_lunar": "Creciente",
            "plagas": ["Psila del pistacho"],
            "enfermedades": ["Alternaria"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -12,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Muy baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Portainjerto muy resistente a sequía y caliza; típico de Castilla-La Mancha."
        },
        {
            "nombre": "Pistachero Kerman",
            "nombre_latin": "Pistacia vera",
            "variedad": "Kerman",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 230,
            "litros_agua_semana": 20,
            "fase_lunar": "Creciente",
            "plagas": ["Psila del pistacho"],
            "enfermedades": ["Alternaria"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -10,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy cultivado en Castilla-La Mancha."
        },
        {
            "nombre": "Pistachero Larnaka",
            "nombre_latin": "Pistacia vera",
            "variedad": "Larnaka",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 225,
            "litros_agua_semana": 20,
            "fase_lunar": "Creciente",
            "plagas": ["Psila"],
            "enfermedades": ["Alternaria"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -10,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente; ideal para secano."
        },
        {
            "nombre": "Pistachero Sirora",
            "nombre_latin": "Pistacia vera",
            "variedad": "Sirora",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 230,
            "litros_agua_semana": 20,
            "fase_lunar": "Creciente",
            "plagas": ["Psila del pistacho"],
            "enfermedades": ["Alternaria"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -10,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy cultivado en Castilla-La Mancha; excelente rendimiento."
        },
        {
            "nombre": "Pistachero Aegina",
            "nombre_latin": "Pistacia vera",
            "variedad": "Aegina",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 225,
            "litros_agua_semana": 20,
            "fase_lunar": "Creciente",
            "plagas": ["Psila"],
            "enfermedades": ["Alternaria"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -10,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente; ideal para zonas cálidas."
        },
        {
            "nombre": "Pistachero Avdat",
            "nombre_latin": "Pistacia vera",
            "variedad": "Avdat",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 235,
            "litros_agua_semana": 21,
            "fase_lunar": "Creciente",
            "plagas": ["Psila"],
            "enfermedades": ["Alternaria"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -10,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy productivo; usado en plantaciones modernas."
        },
        {
            "nombre": "Pistachero Kastel",
            "nombre_latin": "Pistacia vera",
            "variedad": "Kastel",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 240,
            "litros_agua_semana": 21,
            "fase_lunar": "Creciente",
            "plagas": ["Psila"],
            "enfermedades": ["Alternaria"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -10,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente al calor; ideal para Andalucía."
        },

        # ============================================================
        # CASTAÑOS — VARIEDADES ESPAÑOLAS
        # ============================================================

        {
            "nombre": "Castaño Parede",
            "nombre_latin": "Castanea sativa",
            "variedad": "Parede",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 210,
            "litros_agua_semana": 22,
            "fase_lunar": "Creciente",
            "plagas": ["Avispilla del castaño"],
            "enfermedades": ["Chancro"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -12,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy típico de Galicia."
        },
        {
            "nombre": "Castaño Judía",
            "nombre_latin": "Castanea sativa",
            "variedad": "Judía",
            "tipo": "Fruto seco",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 215,
            "litros_agua_semana": 22,
            "fase_lunar": "Creciente",
            "plagas": ["Avispilla"],
            "enfermedades": ["Chancro"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -12,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy apreciada en León y Zamora."
        },

        # ============================================================
        # ALGARROBOS — VARIEDADES ESPAÑOLAS
        # ============================================================

        {
            "nombre": "Algarrobo Común",
            "nombre_latin": "Ceratonia siliqua",
            "variedad": "Común",
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 250,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Cochinilla"],
            "enfermedades": ["Fusarium"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -2,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Muy baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy típico del Mediterráneo; muy resistente a sequía."
        },

        # ============================================================
        # HIGUERAS — VARIEDADES ESPAÑOLAS
        # ============================================================

        {
            "nombre": "Higuera Cuello de Dama Negra",
            "nombre_latin": "Ficus carica",
            "variedad": "Cuello de Dama Negra",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 160,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca de la fruta"],
            "enfermedades": ["Roya"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": -5,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy dulce; típica de Levante."
        },
        {
            "nombre": "Higuera Cuello de Dama Blanca",
            "nombre_latin": "Ficus carica",
            "variedad": "Cuello de Dama Blanca",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 160,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca de la fruta"],
            "enfermedades": ["Roya"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": -5,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy aromática; típica de Cataluña."
        },

        # ============================================================
        # OLIVOS — VARIEDADES ESPAÑOLAS
        # ============================================================

        {
            "nombre": "Olivo Picual",
            "nombre_latin": "Olea europaea",
            "variedad": "Picual",
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 240,
            "litros_agua_semana": 15,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca del olivo"],
            "enfermedades": ["Repilo"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -7,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "La variedad más cultivada en España."
        },
        {
            "nombre": "Olivo Arbequina",
            "nombre_latin": "Olea europaea",
            "variedad": "Arbequina",
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 230,
            "litros_agua_semana": 15,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca del olivo"],
            "enfermedades": ["Repilo"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -6,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy típica de Cataluña; aceite muy aromático."
        }
]

    for c in variedades:
        cultivo = CultivoTipo(**c, user_id=user_id)
        db.add(cultivo)

    db.commit()
    db.close()

    print(">>> Seed de frutos secos y árboles insertado correctamente.")
