# app/seeds/seed_tomates.py

from app.core.database import SessionLocal
from app.models.cultivo_tipo import CultivoTipo

def run(user_id: int = 2):
    db = SessionLocal()

    variedades = [

        # ============================================================
        # TOMATES ESPAÑOLES Y MEDITERRÁNEOS — 50 VARIEDADES REALES
        # ============================================================

        {
            "nombre": "Tomate Kumato",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Kumato",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta", "Mosca blanca", "Pulgón"],
            "enfermedades": ["Mildiu", "Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Fruto oscuro y muy dulce; ideal para ensaladas."
        },

        {
            "nombre": "Tomate Muchamiel",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Muchamiel",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón", "Tuta absoluta"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy típico de Alicante; frutos grandes y carnosos."
        },

        {
            "nombre": "Tomate Corazón de Buey",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Corazón de Buey",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 80,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta", "Trips"],
            "enfermedades": ["Botrytis", "Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy apreciado en el norte; textura mantequillosa."
        },

        {
            "nombre": "Tomate Rosa de Barbastro",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa de Barbastro",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 85,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Tuta absoluta"],
            "enfermedades": ["Mildiu", "Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Tomate aragonés de gran tamaño y sabor dulce."
        },

        {
            "nombre": "Tomate Rosa Mallorquín",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa de Mallorca",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 85,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón", "Mosca blanca"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad isleña muy aromática; piel fina y delicada."
        },

        {
            "nombre": "Tomate Valenciano",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Valenciano",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta", "Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy carnoso; ideal para ensaladas."
        },

        {
            "nombre": "Tomate Montserrat",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Montserrat",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 85,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta", "Trips"],
            "enfermedades": ["Botrytis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy hueco por dentro; ideal para rellenar."
        },

        {
            "nombre": "Tomate De Colgar Mallorquín",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Ramallet",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 95,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Ideal para conservar colgado; típico de Baleares."
        },

        {
            "nombre": "Tomate Negro de Santiago",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Negro de Santiago",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 85,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón", "Trips"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad gallega de sabor intenso y color oscuro."
        },

        {
            "nombre": "Tomate Cherry Negro",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Cherry Negro",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Color oscuro y sabor muy intenso; ideal en mezclas."
        },
                {
            "nombre": "Tomate Cherry Pera",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Cherry Pera Roja",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Racimos muy productivos; ideal para picoteo."
        },
        {
            "nombre": "Tomate Cherry Amarillo",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Cherry Amarillo",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Frutos pequeños y dulces; muy decorativos."
        },
        {
            "nombre": "Tomate Marmande",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Marmande",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 80,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta", "Pulgón"],
            "enfermedades": ["Mildiu", "Botrytis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy usado en Francia y norte de España; frutos acostillados."
        },
        {
            "nombre": "Tomate RAF Tradicional",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "RAF Tradicional",
            "tipo": "Fruto",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta", "Pulgón"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad clásica almeriense; muy dulce."
        },
        {
            "nombre": "Tomate RAF Delizia",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Delizia",
            "tipo": "Fruto",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 95,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Trips"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Selección moderna del RAF; más productivo."
        },
        {
            "nombre": "Tomate Cherry Bombilla",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Bombilla",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 65,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Trips", "Pulgón"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy dulce; ideal para niños."
        },
        {
            "nombre": "Tomate Cherry Chocolate",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Chocolate",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Color marrón rojizo; sabor intenso."
        },
        {
            "nombre": "Tomate Cherry Tigre",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Tiger",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Rayado verde y rojo; muy decorativo."
        },
        {
            "nombre": "Tomate Cherry Verde",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Green Grape",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 75,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Color verde incluso maduro; sabor afrutado."
        },
        {
            "nombre": "Tomate Cherry Rosa",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Pink Cherry",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Color rosado; muy dulce."
        },

        # ============================================================
        # TOMATES DE ENSALADA Y TRADICIONALES
        # ============================================================

        {
            "nombre": "Tomate Moruno",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Moruno",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 85,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy aromático; piel fina."
        },
        {
            "nombre": "Tomate Huevo de Toro",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Huevo de Toro",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Gigante malagueño; muy apreciado."
        },
        {
            "nombre": "Tomate Pera Canario",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Pera Canario",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 75,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 5,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy usado en Canarias; ideal para salsa."
        },
        {
            "nombre": "Tomate Pera Italiano",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "San Marzano",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 5,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "El clásico para salsa italiana."
        },
        {
            "nombre": "Tomate Rosa de Almería",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa Almería",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 85,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy dulce; piel fina."
        },
        {
            "nombre": "Tomate Azul Indigo",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Indigo Rose",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 5,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Color azul púrpura; muy rico en antioxidantes."
        },
        {
            "nombre": "Tomate Green Zebra",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Green Zebra",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 75,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 5,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Rayado verde; sabor ácido y fresco."
        },
        {
            "nombre": "Tomate Cherokee Purple",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Cherokee Purple",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 85,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Botrytis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Color púrpura oscuro; sabor muy profundo."
        },
        {
            "nombre": "Tomate Amarillo Gigante",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Yellow Brandywine",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Frutos enormes y amarillos; muy dulces."
        },
        {
            "nombre": "Tomate Negro Crimea",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Black Krim",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Botrytis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Color oscuro; sabor ahumado."
        },
                {
            "nombre": "Tomate Cherry Pera",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Cherry Pera Roja",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Racimos muy productivos; ideal para picoteo."
        },
        {
            "nombre": "Tomate Cherry Amarillo",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Cherry Amarillo",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Frutos pequeños y dulces; muy decorativos."
        },
        {
            "nombre": "Tomate Marmande",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Marmande",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 80,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta", "Pulgón"],
            "enfermedades": ["Mildiu", "Botrytis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy usado en Francia y norte de España; frutos acostillados."
        },
        {
            "nombre": "Tomate RAF Tradicional",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "RAF Tradicional",
            "tipo": "Fruto",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta", "Pulgón"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad clásica almeriense; muy dulce."
        },
        {
            "nombre": "Tomate RAF Delizia",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Delizia",
            "tipo": "Fruto",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 95,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Trips"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Selección moderna del RAF; más productivo."
        },
        {
            "nombre": "Tomate Cherry Bombilla",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Bombilla",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 65,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Trips", "Pulgón"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy dulce; ideal para niños."
        },
        {
            "nombre": "Tomate Cherry Chocolate",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Chocolate",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Color marrón rojizo; sabor intenso."
        },
        {
            "nombre": "Tomate Cherry Tigre",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Tiger",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Rayado verde y rojo; muy decorativo."
        },
        {
            "nombre": "Tomate Cherry Verde",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Green Grape",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 75,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Color verde incluso maduro; sabor afrutado."
        },
        {
            "nombre": "Tomate Cherry Rosa",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Pink Cherry",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 70,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Color rosado; muy dulce."
        },

        # ============================================================
        # TOMATES DE ENSALADA Y TRADICIONALES
        # ============================================================

        {
            "nombre": "Tomate Moruno",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Moruno",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 85,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy aromático; piel fina."
        },
        {
            "nombre": "Tomate Huevo de Toro",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Huevo de Toro",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Gigante malagueño; muy apreciado."
        },
        {
            "nombre": "Tomate Pera Canario",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Pera Canario",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 75,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 5,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy usado en Canarias; ideal para salsa."
        },
        {
            "nombre": "Tomate Pera Italiano",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "San Marzano",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 5,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "El clásico para salsa italiana."
        },
        {
            "nombre": "Tomate Rosa de Almería",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa Almería",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 85,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy dulce; piel fina."
        },
        {
            "nombre": "Tomate Azul Indigo",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Indigo Rose",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 5,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Color azul púrpura; muy rico en antioxidantes."
        },
        {
            "nombre": "Tomate Green Zebra",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Green Zebra",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 75,
            "litros_agua_semana": 9,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 5,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Rayado verde; sabor ácido y fresco."
        },
        {
            "nombre": "Tomate Cherokee Purple",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Cherokee Purple",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 85,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Botrytis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Color púrpura oscuro; sabor muy profundo."
        },
        {
            "nombre": "Tomate Amarillo Gigante",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Yellow Brandywine",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Frutos enormes y amarillos; muy dulces."
        },
        {
            "nombre": "Tomate Negro Crimea",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Black Krim",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Botrytis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Color oscuro; sabor ahumado."
        },
                {
            "nombre": "Tomate De Ramallet Antiguo",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Ramallet Antiguo",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 95,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Pulgón"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad balear tradicional para colgar; excelente conservación."
        },
        {
            "nombre": "Tomate De Colgar Valenciano Tradicional",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Penjar Tradicional",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 90,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy usado en la Comunidad Valenciana para conserva y pan."
        },
        {
            "nombre": "Tomate Rosa de Barbastro Tardío",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa Tardío",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 95,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Selección tardía del rosa aragonés; frutos enormes."
        },
        {
            "nombre": "Tomate Rosa de Barbastro Temprano",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa Temprano",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 80,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Versión temprana del rosa; muy dulce."
        },
        {
            "nombre": "Tomate De La Cañada",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "La Cañada",
            "tipo": "Fruto",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta"],
            "enfermedades": ["Botrytis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad almeriense de invernadero; muy firme."
        },
        {
            "nombre": "Tomate Raf Conquista",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Conquista",
            "tipo": "Fruto",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 95,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Selección moderna del RAF; muy dulce."
        },
        {
            "nombre": "Tomate Rosa Mallorquín Tradicional",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa Mallorquín",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 85,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy aromático; típico de huertos isleños."
        },
        {
            "nombre": "Tomate De Barbastro Amarillo",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Barbastro Amarillo",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 85,
            "litros_agua_semana": 11,
            "fase_lunar": "Creciente",
            "plagas": ["Trips"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Selección amarilla del rosa; muy dulce."
        },
        {
            "nombre": "Tomate De Colgar de Lleida",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Lleida Colgar",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 90,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy usado en Cataluña para conserva."
        },
        {
            "nombre": "Tomate Rosa de Barbastro Mini",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa Mini",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 75,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Versión pequeña del rosa; muy dulce."
        },
        {
            "nombre": "Tomate De Colgar de Tarragona",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Tarragona Colgar",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 95,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente; ideal para colgar."
        },
        {
            "nombre": "Tomate Rosa de Barbastro Premium",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Rosa Premium",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Tuta absoluta"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Selección gourmet del rosa; muy aromático."
        }
    ]

    for c in variedades:
        cultivo = CultivoTipo(**c, user_id=user_id)
        db.add(cultivo)

    db.commit()
    db.close()

    print(">>> Seed de tomates insertado correctamente.")
