
from app.core.database import SessionLocal
from app.models.cultivo_tipo import CultivoTipo
from app.seeds.seed_plagas import run_all as seed_plagas
from app.seeds.seed_enfermedades import run_all as seed_enfermedades



def run_all(user_id: int = 3):
    print(">>> Cargando TODOS los cultivos en un único seed...")

    db = SessionLocal()
    tipos = []
    tipos.extend([
        {
            "nombre": "General",
            "nombre_latin": None,
            "variedad": None,
            "tipo": "General",
            "temporada_optima": None,
            "dias_crecimiento": None,
            "litros_agua_semana": None,
            "fase_lunar": None,
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": None,
            "frecuencia_tratamiento": None,
            "temperatura_minima": None,
            "temperatura_optima": None,
            "exigencia_hidrica": None,
            "exigencia_nutrientes": None,
            "notas": "Cultivo genérico para asociar enfermedades de catálogo.",
        },
        {
            "nombre": "Albaricoque Búlida",
            "nombre_latin": "Prunus armeniaca",
            "variedad": "Búlida",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 5,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad española muy productiva."
        },
        {
            "nombre": "Albaricoque Canino",
            "nombre_latin": "Prunus armeniaca",
            "variedad": "Canino",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 5,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy cultivado en España."
        },
        {
            "nombre": "Berenjena",
            "nombre_latin": "Solanum melongena",
            "variedad": "Black Beauty",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 80,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 15,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy exigente en calor; evitar encharcamientos."
        },
        {
            "nombre": "Calabacín",
            "nombre_latin": "Cucurbita pepo",
            "variedad": "Black Beauty",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 50,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Cosecha continua; evitar mojar hojas."
        },
        {
            "nombre": "Calabaza",
            "nombre_latin": "Cucurbita maxima",
            "variedad": "Nacional",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 120,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy productiva."
        },
        {
            "nombre": "Ciruela Claudia Verde",
            "nombre_latin": "Prunus domestica",
            "variedad": "Claudia Verde",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 130,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy dulce."
        },
        {
            "nombre": "Ciruela Reina Claudia Amarilla",
            "nombre_latin": "Prunus domestica",
            "variedad": "Reina Claudia Amarilla",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 130,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy apreciada."
        },
        {
            "nombre": "Granado Mollar",
            "nombre_latin": "Punica granatum",
            "variedad": "Mollar de Elche",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 180,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": 5,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad española muy dulce y apreciada."
        },
        {
            "nombre": "Higuera Verdia",
            "nombre_latin": "Ficus carica",
            "variedad": "Verdia",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -2,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Variedad española muy productiva."
        },
        {
            "nombre": "Maíz",
            "nombre_latin": "Zea mays",
            "variedad": "Nacional",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 100,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy productivo."
        },
        {
            "nombre": "Melocotón de Calanda",
            "nombre_latin": "Prunus persica",
            "variedad": "Calanda",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 150,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": -3,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Famoso por su dulzor y tamaño."
        },
        {
            "nombre": "Melón",
            "nombre_latin": "Cucumis melo",
            "variedad": "Piel de Sapo",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 90,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 15,
            "temperatura_optima": 30,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Reducir riego al final para mejorar dulzor."
        },
        {
            "nombre": "Pimiento",
            "nombre_latin": "Capsicum annuum",
            "variedad": "California Wonder",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 75,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Sensibles al frío; requieren suelos bien drenados."
        },
        {
            "nombre": "Pimiento Morrón",
            "nombre_latin": "Capsicum annuum",
            "variedad": "Morrón",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 75,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy típico en la cocina española."
        },
        {
            "nombre": "Sandía",
            "nombre_latin": "Citrullus lanatus",
            "variedad": "Crimson Sweet",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 85,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 16,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Necesita mucho sol y espacio."
        },
        {
            "nombre": "Tomate",
            "nombre_latin": "Solanum lycopersicum",
            "variedad": "Raff",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 90,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 15,
            "temperatura_minima": 10,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Requiere tutorado, poda y riego constante."
        }
    ])
    
    tipos.extend([
        {
            "nombre": "Acelga",
            "nombre_latin": "Beta vulgaris var. cicla",
            "variedad": "Verde Penca Blanca",
            "tipo": "Hoja",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 55,
            "litros_agua_semana": 7,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy productiva; admite cortes sucesivos."
        },
        {
            "nombre": "Achicoria",
            "nombre_latin": "Cichorium intybus",
            "variedad": "Nacional",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 60,
            "litros_agua_semana": 6,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 4,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente; sabor ligeramente amargo."
        },
        {
            "nombre": "Borraja",
            "nombre_latin": "Borago officinalis",
            "variedad": "Nacional",
            "tipo": "Hoja",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 7,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 6,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy usada en Aragón; flores comestibles."
        },
        {
            "nombre": "Cardo Blanco",
            "nombre_latin": "Cynara cardunculus",
            "variedad": "Blanco",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 120,
            "litros_agua_semana": 10,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy típico en la gastronomía española."
        },
        {
            "nombre": "Col Blanca",
            "nombre_latin": "Brassica oleracea var. capitata",
            "variedad": "Blanca",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 90,
            "litros_agua_semana": 10,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy resistente y productiva."
        },
        {
            "nombre": "Col rizada",
            "nombre_latin": "Brassica oleracea var. sabellica",
            "variedad": "Kale",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 70,
            "litros_agua_semana": 8,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": -5,
            "temperatura_optima": 15,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Tolera heladas; mejora sabor con frío."
        },
        {
            "nombre": "Espinaca",
            "nombre_latin": "Spinacia oleracea",
            "variedad": "Gigante de Invierno",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 45,
            "litros_agua_semana": 6,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 4,
            "temperatura_optima": 16,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Prefiere clima fresco; evitar calor extremo."
        },
        {
            "nombre": "Grelos",
            "nombre_latin": "Brassica rapa",
            "variedad": "Nacional",
            "tipo": "Hoja",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 60,
            "litros_agua_semana": 8,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 0,
            "temperatura_optima": 14,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy típico en Galicia."
        },
        {
            "nombre": "Lechuga",
            "nombre_latin": "Lactuca sativa",
            "variedad": "Romana",
            "tipo": "Hoja",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 8,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Cosecha escalonada; sensible al calor."
        },
        {
            "nombre": "Repollo",
            "nombre_latin": "Brassica oleracea var. capitata",
            "variedad": "Tardío",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 90,
            "litros_agua_semana": 10,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Requiere suelos ricos y humedad constante."
        },
        {
            "nombre": "Rúcula",
            "nombre_latin": "Eruca sativa",
            "variedad": "Selvatica",
            "tipo": "Hoja",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 40,
            "litros_agua_semana": 5,
            "fase_lunar": "Nueva",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 6,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Sabor picante; crece muy rápido."
        }
    ])
    
    tipos.extend([
        {
            "nombre": "Ajo Morado de Las Pedroñeras",
            "nombre_latin": "Allium sativum",
            "variedad": "Morao",
            "tipo": "Raíz",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 180,
            "litros_agua_semana": 4,
            "fase_lunar": "Menguante",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "El ajo más famoso de España."
        },
        {
            "nombre": "Cebolla Recas",
            "nombre_latin": "Allium cepa",
            "variedad": "Recas",
            "tipo": "Raíz",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 6,
            "fase_lunar": "Menguante",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad española muy apreciada."
        },
        {
            "nombre": "Chirivía",
            "nombre_latin": "Pastinaca sativa",
            "variedad": "Guernsey",
            "tipo": "Raíz",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 120,
            "litros_agua_semana": 7,
            "fase_lunar": "Menguante",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 2,
            "temperatura_optima": 14,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Mejora sabor tras primeras heladas."
        },
        {
            "nombre": "Nabo",
            "nombre_latin": "Brassica rapa",
            "variedad": "Blanco Globo",
            "tipo": "Raíz",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 55,
            "litros_agua_semana": 6,
            "fase_lunar": "Menguante",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 4,
            "temperatura_optima": 15,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Prefiere clima fresco; rápido crecimiento."
        },
        {
            "nombre": "Puerro",
            "nombre_latin": "Allium porrum",
            "variedad": "Nacional",
            "tipo": "Raíz",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 120,
            "litros_agua_semana": 8,
            "fase_lunar": "Menguante",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente."
        },
        {
            "nombre": "Rábano",
            "nombre_latin": "Raphanus sativus",
            "variedad": "Cherry Belle",
            "tipo": "Raíz",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 30,
            "litros_agua_semana": 5,
            "fase_lunar": "Menguante",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 5,
            "temperatura_optima": 16,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Crecimiento muy rápido; ideal para siembras sucesivas."
        },
        {
            "nombre": "Remolacha",
            "nombre_latin": "Beta vulgaris",
            "variedad": "Detroit",
            "tipo": "Raíz",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 6,
            "fase_lunar": "Menguante",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 6,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Tolera frío; hojas también comestibles."
        },
        {
            "nombre": "Zanahoria",
            "nombre_latin": "Daucus carota",
            "variedad": "Nantesa",
            "tipo": "Raíz",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 75,
            "litros_agua_semana": 6,
            "fase_lunar": "Menguante",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 4,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Prefiere suelos sueltos y profundos."
        }
    ])
    
    tipos.extend([
        {
            "nombre": "Guisante",
            "nombre_latin": "Pisum sativum",
            "variedad": "Rondo",
            "tipo": "Leguminosa",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 70,
            "litros_agua_semana": 6,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 0,
            "temperatura_optima": 16,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy resistente al frío; fijadora de nitrógeno."
        },
        {
            "nombre": "Haba",
            "nombre_latin": "Vicia faba",
            "variedad": "Aguadulce",
            "tipo": "Leguminosa",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 90,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": -2,
            "temperatura_optima": 14,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy típica en España; soporta heladas suaves."
        },
        {
            "nombre": "Judía Perona",
            "nombre_latin": "Phaseolus vulgaris",
            "variedad": "Perona",
            "tipo": "Leguminosa",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 65,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad española muy apreciada."
        },
        {
            "nombre": "Judía Verde",
            "nombre_latin": "Phaseolus vulgaris",
            "variedad": "Strike",
            "tipo": "Leguminosa",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy productiva; requiere riegos constantes."
        },
        {
            "nombre": "Lenteja",
            "nombre_latin": "Lens culinaris",
            "variedad": "Pardina",
            "tipo": "Leguminosa",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 100,
            "litros_agua_semana": 5,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": -2,
            "temperatura_optima": 14,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy rústica; ideal para rotaciones."
        }
    ])
    
    tipos.extend([
        {
            "nombre": "Boniato",
            "nombre_latin": "Ipomoea batatas",
            "variedad": "California",
            "tipo": "Tubérculo",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Prefiere suelos sueltos y cálidos."
        },
        {
            "nombre": "Cúrcuma",
            "nombre_latin": "Curcuma longa",
            "variedad": "Nacional",
            "tipo": "Tubérculo",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 210,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": 15,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Requiere humedad constante y calor."
        },
        {
            "nombre": "Jengibre",
            "nombre_latin": "Zingiber officinale",
            "variedad": "Nacional",
            "tipo": "Tubérculo",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 200,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": 15,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Necesita calor y humedad; evitar sol directo fuerte."
        },
        {
            "nombre": "Patata",
            "nombre_latin": "Solanum tuberosum",
            "variedad": "Kennebec",
            "tipo": "Tubérculo",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 100,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Evitar suelos encharcados; rotar cultivos."
        },
        {
            "nombre": "Yuca",
            "nombre_latin": "Manihot esculenta",
            "variedad": "Dulce",
            "tipo": "Tubérculo",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 240,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": 18,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente a sequía."
        }
    ])

    tipos.extend([
        {
            "nombre": "Albahaca",
            "nombre_latin": "Ocimum basilicum",
            "variedad": "Genovesa",
            "tipo": "Aromática",
            "temporada_optima": "Verano",
            "dias_crecimiento": 60,
            "litros_agua_semana": 6,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy sensible al frío; ideal para asociar con tomate."
        },
        {
            "nombre": "Cilantro",
            "nombre_latin": "Coriandrum sativum",
            "variedad": "Nacional",
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 45,
            "litros_agua_semana": 5,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 8,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Tiende a espigarse con calor."
        },
        {
            "nombre": "Hierbabuena",
            "nombre_latin": "Mentha spicata",
            "variedad": "Nacional",
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 8,
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy invasiva; mejor en maceta."
        },
        {
            "nombre": "Menta",
            "nombre_latin": "Mentha × piperita",
            "variedad": "Piperita",
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy aromática; evitar sol fuerte."
        },
        {
            "nombre": "Orégano",
            "nombre_latin": "Origanum vulgare",
            "variedad": "Mediterráneo",
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 90,
            "litros_agua_semana": 4,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 4,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy resistente; ideal para clima mediterráneo."
        },
        {
            "nombre": "Perejil",
            "nombre_latin": "Petroselinum crispum",
            "variedad": "Rizado",
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 70,
            "litros_agua_semana": 6,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 6,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Germinación lenta; mantener humedad constante."
        },
        {
            "nombre": "Poleo",
            "nombre_latin": "Mentha pulegium",
            "variedad": "Nacional",
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy aromática; ideal para infusiones."
        },
        {
            "nombre": "Romero",
            "nombre_latin": "Rosmarinus officinalis",
            "variedad": "Mediterráneo",
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 3,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -2,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy resistente; ideal para suelos pobres."
        },
        {
            "nombre": "Tomillo",
            "nombre_latin": "Thymus vulgaris",
            "variedad": "Común",
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 90,
            "litros_agua_semana": 3,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -4,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy resistente; ideal para zonas secas."
        }
    ])

    tipos.extend([
        {
            "nombre": "Caléndula",
            "nombre_latin": "Calendula officinalis",
            "variedad": "Nacional",
            "tipo": "Flor",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 6,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Atrae polinizadores; muy usada como planta medicinal."
        },
        {
            "nombre": "Capuchina",
            "nombre_latin": "Tropaeolum majus",
            "variedad": "Nacional",
            "tipo": "Flor",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 50,
            "litros_agua_semana": 6,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 8,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Excelente planta trampa para pulgón."
        },
        {
            "nombre": "Lavanda",
            "nombre_latin": "Lavandula angustifolia",
            "variedad": "Mediterránea",
            "tipo": "Flor",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 3,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -5,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy resistente; atrae abejas."
        },
        {
            "nombre": "Manzanilla",
            "nombre_latin": "Matricaria chamomilla",
            "variedad": "Común",
            "tipo": "Flor",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 70,
            "litros_agua_semana": 5,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 6,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy usada en infusiones; fácil de cultivar."
        },
        {
            "nombre": "Rosa",
            "nombre_latin": "Rosa spp.",
            "variedad": "Híbridos varios",
            "tipo": "Flor",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 150,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": -2,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Requiere podas regulares y buena aireación."
        }
    ])
    
    tipos.extend([
        {
            "nombre": "Albaricoquero",
            "nombre_latin": "Prunus armeniaca",
            "variedad": "Canino",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 150,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -3,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy cultivado en España; frutos dulces."
        },
        {
            "nombre": "Ciruelo",
            "nombre_latin": "Prunus domestica",
            "variedad": "Reina Claudia",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 160,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -4,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Fruto muy dulce y aromático."
        },
        {
            "nombre": "Higuera",
            "nombre_latin": "Ficus carica",
            "variedad": "Cuello de Dama Negra",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 140,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -2,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Variedad muy apreciada en España."
        },
        {
            "nombre": "Manzano",
            "nombre_latin": "Malus domestica",
            "variedad": "Esperiega",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 180,
            "litros_agua_semana": 14,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad española muy dulce y aromática."
        },
        {
            "nombre": "Melocotonero",
            "nombre_latin": "Prunus persica",
            "variedad": "Amarillo de Murcia",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 160,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -3,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy típico en el sureste español."
        },
        {
            "nombre": "Peral",
            "nombre_latin": "Pyrus communis",
            "variedad": "Decana de Comicio",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 170,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -4,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad muy fina y aromática."
        }
    ])

    tipos.extend([
        {
            "nombre": "Albaricoquero",
            "nombre_latin": "Prunus armeniaca",
            "variedad": "Canino",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 150,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -3,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy cultivado en España; frutos dulces."
        },
        {
            "nombre": "Ciruelo",
            "nombre_latin": "Prunus domestica",
            "variedad": "Reina Claudia",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 160,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -4,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Fruto muy dulce y aromático."
        },
        {
            "nombre": "Higuera",
            "nombre_latin": "Ficus carica",
            "variedad": "Cuello de Dama Negra",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 140,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -2,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Variedad muy apreciada en España."
        },
        {
            "nombre": "Manzano",
            "nombre_latin": "Malus domestica",
            "variedad": "Esperiega",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 180,
            "litros_agua_semana": 14,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad española muy dulce y aromática."
        },
        {
            "nombre": "Melocotonero",
            "nombre_latin": "Prunus persica",
            "variedad": "Amarillo de Murcia",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 160,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -3,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy típico en el sureste español."
        },
        {
            "nombre": "Peral",
            "nombre_latin": "Pyrus communis",
            "variedad": "Decana de Comicio",
            "tipo": "Frutal",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 170,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -4,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Variedad muy fina y aromática."
        }
    ])

    tipos.extend([
        {
            "nombre": "Algarrobo",
            "nombre_latin": "Ceratonia siliqua",
            "variedad": "Común",
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 300,
            "litros_agua_semana": 6,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 30,
            "temperatura_minima": -2,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy resistente a sequía; típico del Mediterráneo."
        },
        {
            "nombre": "Fresno",
            "nombre_latin": "Fraxinus angustifolia",
            "variedad": "Nacional",
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 320,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 25,
            "temperatura_minima": -5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy usado en alineaciones y sombra."
        },
        {
            "nombre": "Jacaranda",
            "nombre_latin": "Jacaranda mimosifolia",
            "variedad": "Nacional",
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 300,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 25,
            "temperatura_minima": 0,
            "temperatura_optima": 24,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy ornamental; floración violeta espectacular."
        },
        {
            "nombre": "Olivo",
            "nombre_latin": "Olea europaea",
            "variedad": "Picual",
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 365,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 30,
            "temperatura_minima": -7,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad española líder en producción de aceite."
        }
])
    for t in tipos:
        t["user_id"] = user_id

    # Insertar todos los cultivos
    inserted = 0
    for data in tipos:
        try:
            cultivo = CultivoTipo(**data)
            db.add(cultivo)
            inserted += 1
        except Exception as e:
            print("ERROR insertando:", data.get("nombre"), e)

    db.commit()
    db.close()
    print(f">>> Seed completado: {inserted} cultivos insertados correctamente.")