# app/seeds/seed_variedades_espanolas.py

from app.core.database import SessionLocal
from app.models.cultivo_tipo import CultivoTipo

def run(user_id: int = 2):
    print(">>> Seed: variedades españolas con datos reales")

    db = SessionLocal()

    cultivos = [

        # ---------------------------------------------------------
        # GRANADOS ESPAÑOLES
        # ---------------------------------------------------------
        {
            "nombre": "Granado Mollar",
            "nombre_latin": "Punica granatum",
            "variedad": "Mollar de Elche",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 180,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca", "Pulgón"],
            "enfermedades": ["Alternaria", "Botritis"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": 5,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad española muy dulce y apreciada."
        },

        # ---------------------------------------------------------
        # MANZANOS ESPAÑOLES
        # ---------------------------------------------------------
        {
            "nombre": "Manzano Esperiega",
            "nombre_latin": "Malus domestica",
            "variedad": "Esperiega",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 200,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Carpocapsa", "Pulgón"],
            "enfermedades": ["Moteado", "Oídio"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Manzana típica de Teruel, muy dulce y aromática."
        },
        {
            "nombre": "Manzano Fuji",
            "nombre_latin": "Malus domestica",
            "variedad": "Fuji",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 190,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón", "Carpocapsa"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy productiva y resistente."
        },
        {
            "nombre": "Manzano Golden",
            "nombre_latin": "Malus domestica",
            "variedad": "Golden Delicious",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 180,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Carpocapsa"],
            "enfermedades": ["Moteado"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Una de las variedades más cultivadas en España."
        },

        # ---------------------------------------------------------
        # PERALES ESPAÑOLES
        # ---------------------------------------------------------
        {
            "nombre": "Peral Decana de Comicio",
            "nombre_latin": "Pyrus communis",
            "variedad": "Decana de Comicio",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 170,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Psila", "Pulgón"],
            "enfermedades": ["Fuego bacteriano"],
            "plazo_seguridad": 14,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Pera muy aromática y jugosa."
        },

        # ---------------------------------------------------------
        # MELOCOTONEROS ESPAÑOLES
        # ---------------------------------------------------------
        {
            "nombre": "Melocotonero de Calanda",
            "nombre_latin": "Prunus persica",
            "variedad": "Calanda",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 150,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca de la fruta"],
            "enfermedades": ["Abolladura"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": -3,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Famoso por su dulzor y tamaño."
        },

        # ---------------------------------------------------------
        # HIGUERAS ESPAÑOLAS
        # ---------------------------------------------------------
        {
            "nombre": "Higuera Verdia",
            "nombre_latin": "Ficus carica",
            "variedad": "Verdia",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Cochinilla"],
            "enfermedades": ["Roya"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": -2,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Variedad española muy productiva."
        },

        # ---------------------------------------------------------
        # ÁRBOLES ORNAMENTALES
        # ---------------------------------------------------------
        {
            "nombre": "Jacaranda",
            "nombre_latin": "Jacaranda mimosifolia",
            "variedad": None,
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 300,
            "litros_agua_semana": 15,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 0,
            "temperatura_minima": 5,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Árbol ornamental de flor violeta."
        },
        {
            "nombre": "Fresno común",
            "nombre_latin": "Fraxinus excelsior",
            "variedad": None,
            "tipo": "Árbol",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 250,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": [],
            "enfermedades": [],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 0,
            "temperatura_minima": -10,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Árbol robusto y muy usado en parques."
        },

        # ---------------------------------------------------------
        # AROMÁTICAS
        # ---------------------------------------------------------
        {
            "nombre": "Hierbabuena",
            "nombre_latin": "Mentha spicata",
            "variedad": None,
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Roya"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy invasiva; mejor cultivar en maceta."
        },
        {
            "nombre": "Poleo",
            "nombre_latin": "Mentha pulegium",
            "variedad": None,
            "tipo": "Aromática",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Roya"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Aromática muy usada en infusiones."
        },

        # ---------------------------------------------------------
        # ROSALES (10 variedades)
        # ---------------------------------------------------------
        *[
            {
                "nombre": f"Rosal variedad {i}",
                "nombre_latin": "Rosa spp.",
                "variedad": f"Variedad {i}",
                "tipo": "Flor",
                "temporada_optima": "Primavera",
                "dias_crecimiento": 120,
                "litros_agua_semana": 6,
                "fase_lunar": "Creciente",
                "plagas": ["Pulgón", "Araña roja"],
                "enfermedades": ["Oídio", "Mancha negra"],
                "plazo_seguridad": 0,
                "frecuencia_tratamiento": 14,
                "temperatura_minima": -5,
                "temperatura_optima": 20,
                "exigencia_hidrica": "Media",
                "exigencia_nutrientes": "Alta",
                "notas": "Rosal ornamental."
            }
            for i in range(1, 11)
        ],

        # ---------------------------------------------------------
        # HORTALIZAS ESPAÑOLAS
        # ---------------------------------------------------------
        {
            "nombre": "Calabaza",
            "nombre_latin": "Cucurbita maxima",
            "variedad": "Nacional",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 120,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Mosca blanca"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Media",
            "notas": "Muy productiva."
        },
        {
            "nombre": "Cebolla Recas",
            "nombre_latin": "Allium cepa",
            "variedad": "Recas",
            "tipo": "Raíz",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 120,
            "litros_agua_semana": 6,
            "fase_lunar": "Menguante",
            "plagas": ["Trips"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 5,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Variedad española muy apreciada."
        },
        {
            "nombre": "Ajo Morado de Las Pedroñeras",
            "nombre_latin": "Allium sativum",
            "variedad": "Morao",
            "tipo": "Raíz",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 180,
            "litros_agua_semana": 4,
            "fase_lunar": "Menguante",
            "plagas": ["Trips"],
            "enfermedades": ["Fusarium"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 20,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Baja",
            "exigencia_nutrientes": "Media",
            "notas": "El ajo más famoso de España."
        },
        {
            "nombre": "Maíz",
            "nombre_latin": "Zea mays",
            "variedad": "Nacional",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 100,
            "litros_agua_semana": 12,
            "fase_lunar": "Creciente",
            "plagas": ["Taladro"],
            "enfermedades": ["Roya"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 10,
            "temperatura_optima": 25,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy productivo."
        },
        {
            "nombre": "Puerro",
            "nombre_latin": "Allium porrum",
            "variedad": "Nacional",
            "tipo": "Raíz",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 120,
            "litros_agua_semana": 8,
            "fase_lunar": "Menguante",
            "plagas": ["Trips"],
            "enfermedades": ["Roya"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente."
        },
        {
            "nombre": "Judía Perona",
            "nombre_latin": "Phaseolus vulgaris",
            "variedad": "Perona",
            "tipo": "Leguminosa",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Antracnosis"],
            "plazo_seguridad": 3,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 10,
            "temperatura_optima": 22,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy productiva."
        },
        {
            "nombre": "Haba Aguadulce",
            "nombre_latin": "Vicia faba",
            "variedad": "Aguadulce",
            "tipo": "Leguminosa",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 90,
            "litros_agua_semana": 7,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón negro"],
            "enfermedades": ["Roya"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 2,
            "temperatura_optima": 14,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy resistente al frío."
        },
                {
            "nombre": "Guisante Rondo",
            "nombre_latin": "Pisum sativum",
            "variedad": "Rondo",
            "tipo": "Leguminosa",
            "temporada_optima": "Invierno",
            "dias_crecimiento": 70,
            "litros_agua_semana": 6,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón", "Trips"],
            "enfermedades": ["Mildiu", "Fusarium"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 4,
            "temperatura_optima": 16,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Prefiere climas frescos; muy productivo."
        },

        # ---------------------------------------------------------
        # MÁS HORTALIZAS ESPAÑOLAS (COMPLETAMOS LISTA)
        # ---------------------------------------------------------

        {
            "nombre": "Espinaca Gigante de Invierno",
            "nombre_latin": "Spinacia oleracea",
            "variedad": "Gigante de Invierno",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 45,
            "litros_agua_semana": 6,
            "fase_lunar": "Nueva",
            "plagas": ["Minador", "Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 4,
            "temperatura_optima": 16,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente al frío."
        },
        {
            "nombre": "Acelga Verde Penca Blanca",
            "nombre_latin": "Beta vulgaris var. cicla",
            "variedad": "Verde Penca Blanca",
            "tipo": "Hoja",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 55,
            "litros_agua_semana": 7,
            "fase_lunar": "Nueva",
            "plagas": ["Pulgón", "Mosca de la remolacha"],
            "enfermedades": ["Cercospora"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 5,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy productiva; admite cortes sucesivos."
        },
        {
            "nombre": "Achicoria",
            "nombre_latin": "Cichorium intybus",
            "variedad": "Nacional",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 60,
            "litros_agua_semana": 6,
            "fase_lunar": "Nueva",
            "plagas": ["Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 10,
            "temperatura_minima": 4,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy resistente; sabor ligeramente amargo."
        },
        {
            "nombre": "Cardo Blanco",
            "nombre_latin": "Cynara cardunculus",
            "variedad": "Blanco",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 120,
            "litros_agua_semana": 10,
            "fase_lunar": "Nueva",
            "plagas": ["Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy típico en la gastronomía española."
        },
        {
            "nombre": "Borraja",
            "nombre_latin": "Borago officinalis",
            "variedad": "Nacional",
            "tipo": "Hoja",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 60,
            "litros_agua_semana": 7,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 6,
            "temperatura_optima": 20,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Media",
            "notas": "Muy usada en Aragón; flores comestibles."
        },
        {
            "nombre": "Col Blanca",
            "nombre_latin": "Brassica oleracea var. capitata",
            "variedad": "Blanca",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 90,
            "litros_agua_semana": 10,
            "fase_lunar": "Nueva",
            "plagas": ["Orugas", "Mosca de la col"],
            "enfermedades": ["Mildiu", "Hernia de la col"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy resistente y productiva."
        },
        {
            "nombre": "Repollo Tardío",
            "nombre_latin": "Brassica oleracea var. capitata",
            "variedad": "Tardío",
            "tipo": "Hoja",
            "temporada_optima": "Otoño",
            "dias_crecimiento": 90,
            "litros_agua_semana": 10,
            "fase_lunar": "Nueva",
            "plagas": ["Orugas", "Mosca de la col"],
            "enfermedades": ["Mildiu", "Hernia de la col"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 0,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy usado en guisos tradicionales."
        },
        {
            "nombre": "Zanahoria Nantesa",
            "nombre_latin": "Daucus carota",
            "variedad": "Nantesa",
            "tipo": "Raíz",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 75,
            "litros_agua_semana": 6,
            "fase_lunar": "Menguante",
            "plagas": ["Mosca de la zanahoria"],
            "enfermedades": ["Alternaria"],
            "plazo_seguridad": 0,
            "frecuencia_tratamiento": 12,
            "temperatura_minima": 4,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Baja",
            "notas": "Muy dulce y productiva."
        },
        {
            "nombre": "Pimiento Morrón",
            "nombre_latin": "Capsicum annuum",
            "variedad": "Morrón",
            "tipo": "Fruto",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 75,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Trips", "Pulgón"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 12,
            "temperatura_optima": 26,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy típico en la cocina española."
        },
        {
            "nombre": "Patata Kennebec",
            "nombre_latin": "Solanum tuberosum",
            "variedad": "Kennebec",
            "tipo": "Tubérculo",
            "temporada_optima": "Primavera",
            "dias_crecimiento": 110,
            "litros_agua_semana": 12,
            "fase_lunar": "Menguante",
            "plagas": ["Escarabajo de la patata"],
            "enfermedades": ["Mildiu"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 7,
            "temperatura_optima": 18,
            "exigencia_hidrica": "Alta",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy usada en Galicia y Asturias."
        },
        {
            "nombre": "Melón Piel de Sapo",
            "nombre_latin": "Cucumis melo",
            "variedad": "Piel de Sapo",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 90,
            "litros_agua_semana": 8,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 15,
            "temperatura_optima": 30,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy dulce y resistente."
        },
        {
            "nombre": "Sandía Crimson Sweet",
            "nombre_latin": "Citrullus lanatus",
            "variedad": "Crimson Sweet",
            "tipo": "Fruto",
            "temporada_optima": "Verano",
            "dias_crecimiento": 85,
            "litros_agua_semana": 10,
            "fase_lunar": "Creciente",
            "plagas": ["Pulgón"],
            "enfermedades": ["Oídio"],
            "plazo_seguridad": 7,
            "frecuencia_tratamiento": 14,
            "temperatura_minima": 16,
            "temperatura_optima": 28,
            "exigencia_hidrica": "Media",
            "exigencia_nutrientes": "Alta",
            "notas": "Muy productiva y dulce."
        }
    ]

    # ---------------------------------------------------------
    # INSERCIÓN FINAL
    # ---------------------------------------------------------

    for c in cultivos:
        cultivo = CultivoTipo(
            nombre=c.get("nombre"),
            nombre_latin=c.get("nombre_latin"),
            variedad=c.get("variedad"),
            tipo=c.get("tipo"),
            temporada_optima=c.get("temporada_optima"),
            dias_crecimiento=c.get("dias_crecimiento"),
            litros_agua_semana=c.get("litros_agua_semana"),
            fase_lunar=c.get("fase_lunar"),
            plagas=c.get("plagas"),
            enfermedades=c.get("enfermedades"),
            plazo_seguridad=c.get("plazo_seguridad"),
            frecuencia_tratamiento=c.get("frecuencia_tratamiento"),
            temperatura_minima=c.get("temperatura_minima"),
            temperatura_optima=c.get("temperatura_optima"),
            exigencia_hidrica=c.get("exigencia_hidrica"),
            exigencia_nutrientes=c.get("exigencia_nutrientes"),
            notas=c.get("notas"),
            user_id=user_id
        )
        db.add(cultivo)

    db.commit()
    db.close()

    print(">>> Seed variedades españolas cargado correctamente.")
